#!../../bin/linux-x86_64/wtrvac-freia
#+======================================================================
# $HeadURL: https://svnpub.iter.org/codac/iter/codac/dev/units/m-epics-iter-templates/tags/CODAC-CORE-4.1.0/templates/genericBoot/ioc/st.cmd $
# $Id: st.cmd 35402 2013-04-07 15:41:49Z zagara $
#
# Project       : CODAC Core System
#
# Description   : ITER ioc template EPICS start up file
#
# Author(s)     : This file was generated by CODAC development toolkit
#
# Copyright (c) : 2010-2013 ITER Organization,
#                 CS 90 046
#                 13067 St. Paul-lez-Durance Cedex
#                 France
#
# This file is part of ITER CODAC software.
# For the terms and conditions of redistribution or use of this software
# refer to the file ITER-LICENSE.TXT located in the top level directory
# of the distribution package.
#
#-======================================================================

< envPaths
< envSystem
< envUser

cd "${TOP}"

#############################################
## Register all support components         ##
#############################################

dbLoadDatabase "dbd/wtrvac-freia.dbd"
wtrvac_freia_registerRecordDeviceDriver pdbbase

< "${TOP}/iocBoot/iocwtrvac-freia/sddPreDriverConf.cmd"
< "${TOP}/iocBoot/iocwtrvac-freia/userPreDriverConf.cmd"
< "${TOP}/iocBoot/iocwtrvac-freia/threadSchedulingConf.cmd"
< "${TOP}/iocBoot/iocwtrvac-freia/dbToLoad.cmd"
< "${TOP}/iocBoot/iocwtrvac-freia/iocwtrvac-freia-preSaveRestore.cmd"

#############################################
## IOC Logging                             ##
#############################################
iocLogInit

#############################################
## IOC initialization                      ##
#############################################
cd "${TOP}/db"
iocInit

< "${TOP}/iocBoot/iocwtrvac-freia/iocwtrvac-freia-postSaveRestore.cmd"
< "${TOP}/iocBoot/iocwtrvac-freia/sddSeqToLoad.cmd"
< "${TOP}/iocBoot/iocwtrvac-freia/seqToLoad.cmd"
< "${TOP}/iocBoot/iocwtrvac-freia/sddPostDriverConf.cmd"
< "${TOP}/iocBoot/iocwtrvac-freia/userPostDriverConf.cmd"


